### ISSUE TITLE
HTTP ERROR 400 No video for specified timestamp cameras_controller.generate_network_camera_snapshot()

### ISSUE THREAD

**Issue by yujiterada** [meraki/meraki-python-sdk#4]
### Issue description

The function cameras_controller.generate_network_camera_snapshot() will return HTTP error 400 when timestamp is specified in object GenerateNetworkCameraSnapshotModel() is almost the same as the current time. This means that taking a snapshot with a timestamp converted from the epoch timestamp included in the MQTT feed will not work unless waiting for about 2 minutes after the MQTT feed has been received.

### Steps to reproduce the issue

1. Send MQTT from MV
2. Convert epoch timestamp to ISO8601 timestamp
2. Take a snapshot with the ISO8601 timestamp

### Workaround

Wait for 2 - 3 minutes before taking the snapshot or use cameras_controller.generate_network_camera_snapshot() without specifying the timestamp. The latter will not take the snapshot of the exact same time of the timestamp of the feed though.

**Comment by yujiterada** [comment]
Seems like this is fixed

**Comment by nevin22** [comment]
It's not
